/*

# DSA book:

##### [data structures and algorithms](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####data-structures-and-algorithms)
##### [Introduction](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####introduction)
##### [How DSA gives you an edge](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####how-dsa-gives-you-an-edge)
#### [Technical interviews: many focus on DSA](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####technical-interviews-many-focus-on-dsa)
#### [Efficient Problem solving:](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####efficient-problem-solving)
#### [Building a strong foundation](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####building-a-strong-foundation)
##### [What we'll cover](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####what-well-cover)
#### [PEDAC](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####pedac)
#### [sorting algorithms](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####sorting-algorithms)
#### [algorithm techniques](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####algorithm-techniques)
#### [essential data structures](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####essential-data-structures)
#### [practice for mastery](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-for-mastery)
#### [going deeper](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####going-deeper)
#### [let's get started](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####lets-get-started)
##### [the pedac approach to problem solving](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####the-pedac-approach-to-problem-solving)
##### [introduction to data structures and algorithms](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####introduction-to-data-structures-and-algorithms)
##### [why data structures matter](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####why-data-structures-matter)
#### [what are data structures?](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####what-are-data-structures)
#### [the benefits of data structures](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####the-benefits-of-data-structures)
#### [code efficiency](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####code-efficiency)
#### [algorithm design](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####algorithm-design)
#### [problem solving](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####problem-solving)
#### [a real-world example](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####a-real-world-example)
##### [why algorithms matter](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####why-algorithms-matter)
#### [what are algorithms?](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####what-are-algorithms)
#### [choosing an algorithm](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####choosing-an-algorithm)
##### [introduction to big o notation](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####introduction-to-big-o-notation)
#### [time complexities](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####time-complexities)
#### [big o](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####big-o)
##### [exploring time complexities](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####exploring-time-complexities)
#### [o(1)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####o1)
##### [o(logn)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####ologn)
#### [logarithms](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####logarithms)
#### [exponent](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####exponent)
#### [o(n)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####on)
#### [o(nlogn)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####onlogn)
#### [o(n^2)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####on2)
#### [o(n^3)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####on3)
#### [o(2^n)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####o2n)
#### [o(n!)](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####on)
##### [space complexity](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####space-complexity)
#### [auxiliary space complexity](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####auxiliary-space-complexity)
### [fine-tuning time complexity](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####fine-tuning-time-complexity)
#### [removing constants from time complexity](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####removing-constants-from-time-complexity)
#### [the arbitrary name "n"]](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####arbitrary-name-n)
#### [Distinct variable names for different collections](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####distinct-variable-names-for-different-collections)
##### [Time & Space Complexity Problems](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####time--space-complexity-problems)
#### [Practice problems](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-problems)
##### [Algorithm Discovery Process](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####algorithm-discovery-process)
#### [Pushing the Big O curve down 1 level](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####pushing-the-big-o-curve-down-1-level)
#### [Hash Tables](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####hash-tables)
##### [Practice: Find a Majority Element](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-find-a-majority-element)
#### [Problem descrption](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####problem-descrption)
##### [SORTING ALGORITHMS](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####sorting-algorithms)
##### [Intro to Sorting Algorithms](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####intro-to-sorting-algorithms)
#### [Real World Applications](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####real-world-applications)
##### [Bubble Sort](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####bubble-sort)
##### [Selection Sort](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####selection-sort)
##### [Insertion Sort](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####insertion-sort)
##### [POINTER-BASED MENTAL MODELS](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####pointer-based-mental-models)
##### [Pointer-Based Strategies](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####pointer-based-strategies)
##### [Two Pointers: Start/End](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####two-pointers-startend)
##### [Two Pointers: Anchor/Runner](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####two-pointers-anchorrunner)
#### [Reader-writer variant](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####reader-writer-variant)
##### [Practice: Reverse Consonants](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-reverse-consonants)
##### [Practice: Compress to Distinct](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-compress-to-distinct)
##### [BINARY SEARCH](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####binary-search)
##### [Intro to Binary Search](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####intro-to-binary-search)
##### [Binary Search Template](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####binary-search-template)
#### [Template:](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####template)
##### [Demo: Find Zero Position](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####demo-find-zero-position)
##### [Demo: Find The Range of Threes](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####demo-find-the-range-of-threes)
##### [Practice: Minimum Count](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-minimum-count)
##### [LINKED LISTS](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####linked-lists)
##### [Intro to Linked Lists](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####intro-to-linked-lists)
#### [Arrays vs Linked Lists](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####arrays-vs-linked-lists)
#### [The Structure of a Linked List](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####the-structure-of-a-linked-list)
#### [Types of Linked Lists](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####types-of-linked-lists)
#### [Implementing a Linked List](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####implementing-a-linked-list)
#### [Arrays vs Linked Lists Performance](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####arrays-vs-linked-lists-performance)
#### [Reading](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####reading)
#### [Searching](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####searching)
#### [Inserting](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####inserting)
##### [Deleting](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####deleting)
#### [When to Use Linked Lists?](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####when-to-use-linked-lists)
#### [Insertion & Deletion](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####insertion--deletion)
##### [Demo: Remove Twos](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####demo-remove-twos)
#### [Problem Description](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####problem-description)
#### [Algorithm](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####algorithm)
#### [Walkthrough](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####walkthrough)
#### [Solution Code](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####solution-code)
##### [Pointers in Linked Lists](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####pointers-in-linked-lists)
##### [Dummy Nodes in Linked Lists](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####dummy-nodes-in-linked-lists)
##### [Demo: Reverse Linked List](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####demo-reverse-linked-list)
##### [Practice: Remove Every Second](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-remove-every-second)
##### [STACKS & QUEUES](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####stacks--queues)
##### [Intro to Stacks and Queues](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####intro-to-stacks-and-queues)
#### [Core Characteristics](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####core-characteristics)
##### [Stacks](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####stacks)
#### [Key operations](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####key-operations)
#### [Practical Applications of Stacks](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practical-applications-of-stacks)
#### [Function call management](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####function-call-management)
#### [Undo mechanisms in Applications](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####undo-mechanisms-in-applications)
#### [Web Browser Navigation](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####web-browser-navigation)
#### [Depth-first Search (DFS) in Graphs](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####depth-first-search-dfs-in-graphs)
##### [Implement Stack with Linked List](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####implement-stack-with-linked-list)
##### [Queues](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####queues)
#### [Key operations](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####key-operations-1)
#### [Practical applications of queues](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practical-applications-of-queues)
##### [Implement Queue using Linked List](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####implement-queue-using-linked-list)
##### [Stacks and Queues in Interviews](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####stacks-and-queues-in-interviews)
#### [When to use a Stack](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####when-to-use-a-stack)
#### [When to use a Queue](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####when-to-use-a-queue)
##### [Practice: Matching Brackets](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####practice-matching-brackets)
##### [CONCLUSION](https://github.com/SandyRodger/launch_school_books/blob/main/data_structures_and_algorithms.md#####conclusion)

*/